### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by pbteja1998** [mit123suki/next-ant-css#2]
Hey, I tried to use the setup that is in this repo. I am geting following error when I ran `yarn build`, and after that `next start`.  But it is not throwing any error when ran `yarn dev`. 

```
....node_modules/antd/es/layout/index.js:1
import Layout from './layout';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.srYc (.....next/server/static/BEY0XCMQwpFyAGnuVDrpv/pages/_app.js:573:18)
    at __webpack_require__ (.....next/server/static/BEY0XCMQwpFyAGnuVDrpv/pages/_app.js:23:31)
    at Module.hUgY (.....next/server/static/BEY0XCMQwpFyAGnuVDrpv/pages/_app.js:386:15)
```

My .babelrc file
```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": "index.css"
      }
    ],
    [
      "import",
      {
        "libraryName": "@ant-design/icons",
        "libraryDirectory": "es/icons",
        "camel2DashComponentName": false
      },
      "@ant-design/icons"
    ]
  ]
}

```

My `next.config.js`

```
const withPlugins = require('next-compose-plugins')
const withBundleAnalyzer = require('@next/bundle-analyzer')
const AntdDayjsWebpackPlugin = require('antd-dayjs-webpack-plugin')

const bundleAnalyzerConfig = {
  enabled: process.env.ANALYZE === 'true',
}

const nextConfig = {
  env: {},
}

module.exports = withPlugins(
  [
    {
      webpack(config, { buildId, dev, isServer, defaultLoaders, webpack }) {
        config.plugins.push(new AntdDayjsWebpackPlugin())
        return config
      },
    },
    withBundleAnalyzer(bundleAnalyzerConfig),
  ],
  nextConfig
)

```

I use typescript for my development. Don't know if this matters.
My tsconfig.json
```

{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ]
}

```

**Comment by pbteja1998** [comment]
The error is gone after changing the `.babelrc` to the following.

```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": "index.css"
      }
    ]
  ]
}
```

**Comment by mit123suki** [comment]
Can i see your package.json? 
What version of node are you running ?

**Comment by pbteja1998** [comment]
@mit123suki  Here is my `package.json`
```
{
  "name": "learning-platform",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "lint": "eslint --fix --ext .js,.jsx,.ts,.tsx --ignore-path .gitignore .",
    "gen": "graphql-codegen --config codegen.yml && yarn lint",
    "dev": "cross-env NODE_OPTIONS=\"-r esm\" next",
    "build": "cross-env NODE_OPTIONS=\"-r esm\" next build",
    "analyze": "cross-env-shell NODE_OPTIONS=\"-r esm\" ANALYZE=true next build",
    "start": "next start"
  },
  "dependencies": {
    "@ant-design/icons": "^4.1.0",
    "@next/bundle-analyzer": "^9.1.4",
    "antd": "4.1.5",
    "antd-dayjs-webpack-plugin": "1.0.0",
    "babel-plugin-import": "1.13.0",
    "cookie": "^0.4.1",
    "cross-env": "^7.0.2",
    "dayjs": "1.8.25",
    "draft-js": "^0.11.5",
    "esm": "^3.2.25",
    "graphql": "^15.0.0",
    "isomorphic-unfetch": "^3.0.0",
    "js-cookie": "^2.2.1",
    "next": "9.3.5",
    "next-compose-plugins": "2.2.0",
    "next-urql": "^0.3.7",
    "nprogress": "^0.2.0",
    "postcss-preset-env": "^6.7.0",
    "react": "16.13.1",
    "react-beautiful-dnd": "^13.0.0",
    "react-dom": "16.13.1",
    "react-is": "^16.13.1",
    "slugify": "^1.4.0",
    "url-join": "^4.0.1",
    "urql": "^1.9.7"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^1.13.3",
    "@graphql-codegen/typescript": "1.13.3",
    "@graphql-codegen/typescript-document-nodes": "1.13.3",
    "@graphql-codegen/typescript-graphql-files-modules": "1.13.3",
    "@graphql-codegen/typescript-operations": "1.13.3",
    "@types/cookie": "^0.3.3",
    "@types/draft-js": "^0.10.40",
    "@types/js-cookie": "^2.2.6",
    "@types/node": "^13.13.4",
    "@types/nprogress": "^0.2.0",
    "@types/react": "^16.9.34",
    "@types/react-beautiful-dnd": "^12.1.2",
    "@types/url-join": "^4.0.0",
    "@typescript-eslint/eslint-plugin": "2.30.0",
    "@typescript-eslint/parser": "2.30.0",
    "babel-eslint": "10.x",
    "eslint": "6.x",
    "eslint-config-prettier": "^6.11.0",
    "eslint-config-react-app": "^5.2.1",
    "eslint-plugin-flowtype": "4.x",
    "eslint-plugin-import": "2.x",
    "eslint-plugin-jsx-a11y": "6.x",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-react": "7.x",
    "eslint-plugin-react-hooks": "3.0.0",
    "husky": ">=4",
    "lint-staged": ">=10",
    "prettier": "2.0.5",
    "typescript": "^3.8.3"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,ts,tsx,jsx}": "yarn lint"
  }
}
```

I am using node 12.16.2

**Comment by mit123suki** [comment]
hey, can you replace your start script to use esm and see if it's fixes the issue without changing babel config ?

```
 "start": "cross-env NODE_OPTIONS=\"-r esm\" next start"

```

**Comment by pbteja1998** [comment]
@mit123suki Yes, changing the start script like above fixes the issue, without changing babel config.

**Comment by pbteja1998** [comment]
@mit123suki I have a few questions. Is there a way to override antd less variables with the current setup?

**Comment by mit123suki** [comment]
If you mean overall theme? then, no way. Use ant-less setup for that

**Comment by pbteja1998** [comment]
Yeah I meant overall theme, like when I try to use `<Button type='primary' />` I want to have different color.

Is it possible to do so, if I use your setup in next-ant-less. If yes, will there be any disadvantages of using that over this?

**Comment by pbteja1998** [comment]
And I saw that you added complete antd css file to _app.js, Is that necessary? Or is there a way around that?

**Comment by mit123suki** [comment]
yes, with-antd-less-setup it's possible as ant uses less as styling language and exposes variables to customize theme. Btw i believe you will also get the same error, try changing start script to use esm in next-less-setup.

Regarding importing antd css file, you can remove it but you'd face style order conflicts. If that doesn't bother you, try changing babelrc file to use style: true, using it imports antd lib any way. If you don't change babelrc and remove that import from antd lib from _app js, you will now only have css files related to components and the whole styling breaks. Cuz antd styling is quite complex and depends on styles from antd lib file

**Comment by pbteja1998** [comment]
Got it. Thanks for explanation.
